//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace planviajes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public string Nombre { get; set; }
        public int Cedula { get; set; }
        public Nullable<int> Clave { get; set; }
        public Nullable<int> Totalfondos { get; set; }
    }
}
